Error
line 91,
    st.image(filenames[idx], caption = f"similar image: {rank}", width = 500)
TypeError: only integer scalar arrays can be converted to a scalar index